namespace Yugioh.Cards.CardProperties
{
    enum MonsterSubType
    {
        AQUA,
        BEAST,
        BEAST_WARRIOR,
        CYBERSE,
        DINOSAUR,
        DIVINE_BEAST,
        DRAGON,
        FAIRY,
        FIEND,
        FISH,
        INSECT,
        MACHINE,
        PLANT,
        PSYCHIC,
        PYRO,
        REPTILE,
        ROCK,
        SEA_SERPENT,
        SPELLCASTER,
        THUNDER,
        WARRIOR,
        WINGED_BEAST,
        WYRM,
        ZOMBIE,
        NONE
    }
}
